name: deploy

on:
  push:
    branches: [master] # master 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    #关键配置
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: install node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.X'
      - name: install deps
        run: npm install
      - name: build app
        run: npm run build
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          #需要部署的文件地址
          source: 'dist/*'
          # SSH address  服务器地址
          host: ${{ secrets.REMOTE_HOST }}
          # Remote dir path  服务器下部署文件存放路径
          target: ${{ secrets.REMOTE_PATH }}
          # SSH Port  服务器端口
          port: 22
          # SSH User name   用户名
          username: ${{ secrets.USER_NAME }}
          # SSH User password  用户密码
          password: ${{ secrets.PASSWORD }}
          # key  密匙
#          key: ${{ secrets.MYSERVER }}
